//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVN.OEE.CHART.Models.OEE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OEEEntities : DbContext
    {
        public OEEEntities()
            : base("name=OEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int OEE1v2(Nullable<System.DateTime> v_FROMDATE, Nullable<System.DateTime> v_TODATE, string v_CATEGORYID, string v_CustomerID, string v_USERID, Nullable<int> v_Phase)
        {
            var v_FROMDATEParameter = v_FROMDATE.HasValue ?
                new ObjectParameter("V_FROMDATE", v_FROMDATE) :
                new ObjectParameter("V_FROMDATE", typeof(System.DateTime));
    
            var v_TODATEParameter = v_TODATE.HasValue ?
                new ObjectParameter("V_TODATE", v_TODATE) :
                new ObjectParameter("V_TODATE", typeof(System.DateTime));
    
            var v_CATEGORYIDParameter = v_CATEGORYID != null ?
                new ObjectParameter("V_CATEGORYID", v_CATEGORYID) :
                new ObjectParameter("V_CATEGORYID", typeof(string));
    
            var v_CustomerIDParameter = v_CustomerID != null ?
                new ObjectParameter("V_CustomerID", v_CustomerID) :
                new ObjectParameter("V_CustomerID", typeof(string));
    
            var v_USERIDParameter = v_USERID != null ?
                new ObjectParameter("V_USERID", v_USERID) :
                new ObjectParameter("V_USERID", typeof(string));
    
            var v_PhaseParameter = v_Phase.HasValue ?
                new ObjectParameter("V_Phase", v_Phase) :
                new ObjectParameter("V_Phase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OEE1v2", v_FROMDATEParameter, v_TODATEParameter, v_CATEGORYIDParameter, v_CustomerIDParameter, v_USERIDParameter, v_PhaseParameter);
        }
    }
}
